services:
  image-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        APP_NAME: image-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./data/images:/app/data/images
    env_file:
      - .env