name: Rust Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.95.0

      - name: Update apt packages
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install -y libdav1d7 libdav1d-dev nasm libhwy-dev libbrotli-dev

      - name: Install libjxl from local directory
        run: |
          cd ./data/libjxl/
          sudo dpkg -i libjxl_0.11.1_amd64.deb libjxl-dev_0.11.1_amd64.deb
          sudo ldconfig
          pkg-config --cflags --libs libjxl

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test
